# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='keyterm',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
