# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_slide_keyterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='content',
        ),
    ]
