# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_remove_slide_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.DecimalField(decimal_places=0, max_digits=10)),
                ('index', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
