# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_sindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slidekeyterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('keyterm', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='slide',
            name='keyterm',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AddField(
            model_name='slide',
            name='chapter',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='page',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='subchapter',
            field=models.DecimalField(decimal_places=0, default=-1, max_digits=10),
            preserve_default=False,
        ),
    ]
