# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20170119_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeytermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k1', models.CharField(max_length=256)),
                ('k2', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='SIndex',
        ),
    ]
