# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_auto_20170119_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('prev_ch', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cur_ch', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ch_time', models.CharField(max_length=256)),
                ('prev_subch', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cur_subch', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subch_time', models.CharField(max_length=256)),
                ('prev', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cur', models.DecimalField(decimal_places=0, max_digits=10)),
                ('time', models.CharField(max_length=256)),
            ],
        ),
    ]
