# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_videoattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slide',
            name='video_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
