# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_sumpagetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapVideoAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('chapter3time', models.CharField(max_length=256)),
                ('chapter10time', models.CharField(max_length=256)),
            ],
        ),
    ]
